# Generated by Django 4.0.1 on 2022-01-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_alter_pizza_options_alter_topping_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ingredients',
            },
        ),
        migrations.RemoveField(
            model_name='topping',
            name='name',
        ),
        migrations.AddField(
            model_name='topping',
            name='ingredients',
            field=models.ManyToManyField(to='pizzas.Ingredient'),
        ),
    ]
